# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed50372a4e1735faa832a753e2d875d0341d600e2f95f2876d959e9394939f5d5a5cb5b1581d2581e29b2abf2b1ba78484ef8a0bd29d4d5131236172c46d9a42

test:
  secret_key_base: 22356e2e82ad9506690506ac98226c08deefea9d4a0dc31217b6e5dfa8360e473d1316e9f23471d76aaddd4520a28f0601a6422840e7617a4f2d021906d29103

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
